title: Rosanna Rossington
description: Portfolio & Blog
url: # site url
avatar: /assets/img/logo.png
favicon: #/assets/img/favicon.ico
google_analytics: # google analytics id
disqus_shortname: # disqus_shortname for disqus comment system

about:
  - paragraph: Having worked in ecommerce roles using HTML and CSS and produced a theoretical website in my dissertation, I have always been intrigued by how technology can be used to merge the online and offline worlds. Eager to be able to create these ideas and see a project through to completion I decided General Assembly was the perfect environment for me to begin my career as a Web Developer. <p>?link?,?link?,?link?</p>
    text_align: center
    links:
      - name: GitHub
        url: https://github.com/RosannaRossington
        external: true
      - name: LinkedIn
        url: https://uk.linkedin.com/in/rosannarossington
        external: true
      - name: Technologies
        url: /technologies
        external: false
