title: About Me
description: Portfolio & Blog
url: # site url
avatar: /assets/img/Logo140.jpg
favicon: #/assets/img/favicon.ico
google_analytics: # google analytics id
disqus_shortname: # disqus_shortname for disqus comment system

about:
  - paragraph: Hi, My name is Rosanna Rossington. Having worked in ecommerce roles using HTML and CSS and produced a theoretical website for Chanel in my dissertation, I have always been intrigued by how technology can be used to merge the online and offline worlds. Eager to be able to create these ideas and see a project through to completion I decided ?link? was the perfect environment for me to begin my career as a Web Developer. <p>?link?,?link?</p><p>?link?,?link?</p>
    text_align: center
    links:
      - name: GeneralAssembly
        url: https://generalassemb.ly/
        external: true
      - name: GitHub
        url: https://github.com/RosannaRossington
        external: true
      - name: LinkedIn
        url: https://uk.linkedin.com/in/rosannarossington
        external: true
      - name: technologies
        url: /technologies
        external: false
      - name: portfolio
        url: /portfolio
        external: false
      # - name: me
      #   url: /me
      #   external: false
